apiVersion: v1
kind: Service
metadata:
  name: fastsync
  labels:
    app: fastsync
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: fastsync