apiVersion: v1
kind: Service
metadata:
  name: data-dude
  labels:
    app: data-dude
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: data-dude