apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta-syncer
  labels:
    app: beta-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta-syncer
  template:
    metadata:
      labels:
        app: beta-syncer
    spec:
      containers:
        - name: beta-syncer
          image: ghcr.io/fireacademy/beta-syncer:1.0.1
          env:
            - name: LEAFLET_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: beta
                  key: LEAFLET_BASE_URL
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: beta
                  key: DB_CONNECTION_STRING
          resources:
            requests:
              cpu: "1"
              memory: "0.5G"
            limits:
              cpu: "1"
              memory: "0.5G"
