apiVersion: v1
kind: Service
metadata:
  name: golden-gate
  labels:
    app: golden-gate
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: golden-gate