apiVersion: apps/v1
kind: Deployment
metadata:
  name: catchpole
  labels:
    app: catchpole
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: catchpole
  template:
    metadata:
      labels:
        app: catchpole
    spec:
      containers:
        - name: catchpole
          image: ghcr.io/fireacademy/catchpole:1.3.5
          env:
            - name: CATCHPOLE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: catchpole
                  key: CATCHPOLE_CONFIG
            - name: CATCHPOLE_LISTEN_PORT
              valueFrom:
                secretKeyRef:
                  name: catchpole
                  key: CATCHPOLE_LISTEN_PORT
            - name: GOLDEN_GATE_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: catchpole
                  key: GOLDEN_GATE_ADDRESS
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_CONNECTION_STRING
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: otlp_endpoint
            - name: INSECURE_MODE
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: insecure
            - name: SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: catchpole_service_name
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              cpu: "333m"
              memory: "500Mi"
            limits:
              cpu: "333m"
              memory: "500Mi"
          startupProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 1
            failureThreshold: 3 
            periodSeconds: 5
