apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: leaflet-testnet10
  labels:
    app: leaflet-testnet10
    service: leaflet-testnet10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaflet-testnet10
      service: leaflet-testnet10
  serviceName: leaflet-testnet10
  template:
    metadata:
      labels:
        app: leaflet-testnet10
        service: leaflet-testnet10
    spec:
      containers:
        - name: leaflet
          image: ghcr.io/fireacademy/leaflet:1.3.5
          volumeMounts:
            - mountPath: /root/.chia
              name: chia-testnet10-db
          env:
            - name: FASTSYNC_CMD
              valueFrom:
                secretKeyRef:
                  name: fastsync-testnet10
                  key: cmd
            - name: LEAFLET_LISTEN_PORT
              valueFrom:
                secretKeyRef:
                  name: leaflet
                  key: LEAFLET_LISTEN_PORT
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: otlp_endpoint
            - name: INSECURE_MODE
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: insecure
            - name: SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: leaflet_testnet10_service_name
            - name: testnet
              value: "true"
          ports:
            - name: http
              containerPort: 18444
          resources:
            requests:
              cpu: "3"
              memory: "6G"
      volumes:
        - name: chia-testnet10-db
          configMap:
            name: chia-testnet10-db
      initContainers:
        - name: chia-testnet10-db-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/root/.chia"]
          volumeMounts:
            - name: chia-testnet10-db
              mountPath: /root/.chia
  volumeClaimTemplates:
  - metadata:
      name: chia-testnet10-db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 200G
      storageClassName: "do-block-storage"