apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: leaflet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: leaflet
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleUp:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 1200
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 69
        # Leaflet requests 3 CPUs, but uses 4
        # -> aim for.69 * 3 = 2.07 CPUs used per instance
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 6G