apiVersion: v1
kind: Service
metadata:
  name: leaflet
  labels:
    app: leaflet
spec:
  ports:
    - name: http
      protocol: TCP
      port: 18444
      targetPort: 18444
  selector:
    app: leaflet